### ISSUE TITLE
Dot product should not be limited to -1 to 1

### ISSUE THREAD

**Issue by SolarLune** [quartercastle/vector#28]
Hello! I actually wrote a PR for this repo a few months ago to fix an issue where Vector.Dot() was returning NaN values due to possibly floating point inaccuracies (#26). While I think the idea is good and there was an issue with NaN values, I now find that dot products can exceed the range of -1 to 1, which is incorrect. 

This should probably be rolled back, though what would be the ideal fix, I'm not exactly sure just yet.

I stumbled on this when I found that I need dot products that exceed -1 to 1 for doing axis projections for SAT intersection testing for games.

**Comment by quartercastle** [comment]
Hi @SolarLune, sorry for the late response. I will roll the PR back for now. Feel free to open a PR if you find a better solution for the NaN issue. :)
